language: go

go:
  - 1.13
  #- tip

env:
- GO111MODULE=on

before_install:
  - go get golang.org/x/tools/cmd/goimports
  - curl -s https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh

script:
  - test -z "$(goimports -d ./ 2>&1)"
  - ./bin/golangci-lint run
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - test "$TRAVIS_GO_VERSION" = "1.13" && bash <(curl -s https://codecov.io/bash)
